# Conexao com o banco de dados PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_de_dados_gerenciador_assinaturas
spring.datasource.username=postgres
spring.datasource.password=wwxx13N

# Configuracoes do Hibernate
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra no console os comandos SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configuracao terminal

spring.output.ansi.enabled = ALWAYS

# Porta do servidor web
server.port=8080